version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: jan-api-gateway-postgres
    environment:
      POSTGRES_DB: jan_api_gateway
      POSTGRES_USER: jan_user
      POSTGRES_PASSWORD: jan_password
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U jan_user -d jan_api_gateway"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

volumes:
  postgres_data:
