replicaCount: 1

image:
  repository: jan-api-gateway
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8080

env: []
#   - name: JAN_INFERENCE_MODEL_URL
#     value: http://jan-inference-model:8080

resources: {}